#!/usr/bin/python
# -*- coding: utf8 -*-

# TODO:

# единицы измерения номиналов при создании пикадовой схемы писать строго обязательно:
# (kOhm, MOhm, pF). При задании номинала конденсатора в P-CAD писать в следующем
# порядке: вольтаж, емкость, процентность использовать исключительно латиницу:
# uF, V

# Сжимать позиционные обозначения по горизонтали, только если одно из них
# перевалило за 10

# Функция pe3 содержит данные, почти готовые для создания спецификации. Надо
# их или временно сохранить и потом передать дальше, или вынести это в одну
# (несколько?) внешнюю функцию



#print tab.dtype.names


import string
import re
import os
import tabular as tb
from operator import itemgetter # for sort() and sorted()
import argparse
import sys

import prepare
import utils
import pe3
from globalvars import *


def deleterow(input_tab, m): #{{{
    """ Функция удаления рядов из таблицы.

    Принимает входную таблицу и номер ряда, который надо удалить.

    Возвращает таблицу без указанного ряда.

    Удалить напрямую нельзя, зато можно откусить 2 куска,
    а потом склеить их вместе.
    """
    if m == 0:
        return input_tab[1:]
    elif m == len(tmp_tab):
        return input_tab[:-1]
    else:
        aa = input_tab[:m]
        bb = input_tab[(m+1):]

    aa = aa.rowstack(bb)
    aa = prepare.columnwider(aa) # раздуем таблицу

    return aa
#}}}
def savelatex(filename, array): #{{{
    """ Функция сохранения таблицы в файл.

    Принимает имя выходного файла и таблицу, которую надо сохранить

    Не возвращает ничего

    Функция сохранения, встроенная в tabular, вписывает названия колонок в
    первую строку выходного файла. Нам это не подходит. Придется удалять уже
    после сохранения файла на диск.
    """

    array.saveSV('table.tmp', delimiter='&')

    f = open('table.tmp','r')
    aa = f.readlines()
    aa = aa[1:]
    f.close()

    f = open(filename,'w')
    m = 0
    while m < len(aa):
        f.write(aa[m])
        m += 1
    f.close()

    os.remove('table.tmp')
#}}}



# command line parser {{{
parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        # Usage text
        description=('''\
------------------------ P-CAD section ---------------------------------------

Open schematic design in P-CAD. Go to menu File -> Reports.
You will see configuration dialog. Tune them.

Report destination: File
Style Format: Separated List
List Separator: &
Reports to generate: check only "Attributes (atr)"

Press "Customize"
  On tab "Format":
    Ensure that "Include Column Header" is checked (by default is checked)
  On tab "Selection":
    Chose needed component attributes (all by default)
  On tab "Sort":
    "Selected Field" must be "RefDes" (by default)
  Other tabs leave as is.
  Press "OK"

On main dialog specify output filename
Press "Generate"

  Note: You may record all this actions to P-CAD macro, and call them later.

Now you have list of components.
Process generated list by this script.


------------------------ Script section --------------------------------------
'''))

parser.add_argument('input_file',
        metavar='filename',
        type=file,
        help='path to file, generated by P-CAD')

parser.add_argument('-p','--pe3',
        metavar='FILENAME',
        type=str,
        default='pe3_table.tex',
        help='save pe3 to %(metavar)s (default: %(default)s)')

parser.add_argument('-s','--spec',
        metavar='FILENAME',
        type=str,
        default='spec_table.tex',
        help='save specification to %(metavar)s (default: %(default)s)')

parser.add_argument('-b','--bill',
        metavar='FILENAME',
        type=str,
        default='bill_table.tex',
        help='save bill list to %(metavar)s (default: %(default)s)')

args = parser.parse_args()

# cleaning input file and reading it to table
# read input file to the buffer
raw_input_file = args.input_file.readlines()

out = open('cleaned_output.tmp','w')
out = open('cleaned_output.tmp','r+')

# delete empty lines and redundant quotes
for line in (raw_input_file):
    # использование в регулярках '$' тут почему-то не прокатывает
    # \r\n - виндовый конец строки, \n - юниксовый, так, на всякий случай
    if re.search('^[    ]*\r\n|^[    ]*\n', line) == None: # if string non empty
        line = re.sub('"','',line) # delete all quotes
        line = re.sub('[ ]*&[ ]*','&',line) # delete unneeded spaces
        # screaning latex special symbols
        line = re.sub('\\\\','\\\\textbackslash ',line)
        line = re.sub('%','\%',line)
        line = re.sub('_','\_',line)
        line = re.sub('#','\#',line)
        line = re.sub('\^','\^',line)
        line = re.sub('~','\~',line)
        line = re.sub('{','\{',line)
        line = re.sub('}','\}',line)
        line = re.sub('\$','\$',line)
        out.write(line)

# Hack!
# This line tells tabarray, that all columns contain string values
# not a numbers. Remove it after loading file
last_line = re.sub('[\t]','fake\t',raw_input_file[0])
out.write(last_line)
out.close()

# reading file into array
raw = tb.tabarray(SVfile = "cleaned_output.tmp",delimiter = '\t')
raw = raw[:-1] # remove hack-line
raw = utils.columnwider(raw)
tmp_tab = raw # create temporal array
os.remove("cleaned_output.tmp") # remove temporal file
#}}}

# create common data base for later processing
bd = prepare.prepare(raw)

# build component list PE3
pe3_array = pe3.pe3(bd)

# save table to file
savelatex(args.pe3, pe3_array)









# автоматический aggregate годится только для генерации спецификации
# aggregate rows
#def refdes_agg(i):
#   return i[0]
#
#tmp_tab = raw.aggregate(On=['Title','Type','SType','Value','Docum','Addit','Note','OrderCode'])
#
#print tmp_tab
#




